name: ESLint

on:
  pull_request:
    branches:
      - trunk

jobs:
  changed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: changed-files
        uses: tj-actions/changed-files@v19
        with:
          files: |
            **/*.js
      - name: Set PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          tools: composer:v2
          coverage: none
      - name: Install dependencies
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        run: composer install
      - name: NPM Install
        run: npm install
      - name: Run ESLint
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        run: npm run lint:js ${{ steps.changed-files.outputs.all_changed_files }}
