name: Generate ZIP file

on:
  workflow_dispatch:
  workflow_call:

jobs:
    generate-zip-file:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup node version and npm cache
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'npm'

            - name: Install Node dependencies
              run: npm ci --no-optional

            - name: Generate ZIP file
              run: npm run prebuild && npm run build:webpack && npm run archive && rm -rf ./woocommerce-accommodation-bookings && unzip woocommerce-accommodation-bookings.zip -d ./woocommerce-accommodation-bookings

            - name: Use the Upload Artifact GitHub Action
              uses: actions/upload-artifact@v3
              with:
                  name: woocommerce-accommodation-bookings
                  path: woocommerce-accommodation-bookings/
